tag_names = ["path"]

[dataframes.__matrix__]
path = { __call__ = ["niarb.io", "iterdir"], path = "fits", pattern = "*.pt", indices = { __indices__ = { __environ__ = "INDICES" } } }

[[dataframes.__include__]]
func = ["niarb.dataframe", "pivot"]
columns = ["variable", "Postsynaptic", "Presynaptic"]
values = "value"
template = '{variable}[{Postsynaptic},{Presynaptic}]'

[dataframes.__include__.aux_columns]
# note that gW is an unsigned matrix here
'$\mathrm{det}(\mathbf{W})$' = '`gW[PYR,PV]` * `gW[PV,PYR]` - `gW[PYR,PYR]` * `gW[PV,PV]`'
'$w_\mathrm{EE} - |w_\mathrm{II}|$' = '`gW[PYR,PYR]` - `gW[PV,PV]`'
'$w_\mathrm{EE}$' = '`gW[PYR,PYR]`'
'$|w_\mathrm{II}|$' = '`gW[PV,PV]`'
'$\kappa_\mathrm{EI}\kappa_\mathrm{IE}$' = '`kappa[PYR,PV]` * `kappa[PV,PYR]`'
'$\tilde{w}_\mathrm{EI}\tilde{w}_\mathrm{IE}$' = '`gW[PYR,PV]` * `gW[PV,PYR]` * `kappa[PYR,PV]` * `kappa[PV,PYR]`'
'$\tilde{w}_\mathrm{EI}\tilde{w}_\mathrm{IE} - \tilde{w}_\mathrm{EE}\tilde{w}_\mathrm{II}$' = '''
0.25 * (`gW[PYR,PV]` * `gW[PV,PYR]` * `kappa[PYR,PV]` * `kappa[PV,PYR]` - `gW[PYR,PYR]` * `gW[PV,PV]` * `kappa[PYR,PYR]` * `kappa[PV,PV]`)'''
'$\tilde{w}_\mathrm{EE}$' = '0.5 * `gW[PYR,PYR]` * `kappa[PYR,PYR]`'

[dataframes.__include__.df]
__call__ = ["niarb.dataframe", "from_state_dict"]
dims = { gW = ["Postsynaptic", "Presynaptic"], sigma = ["Postsynaptic", "Presynaptic"], kappa = ["Postsynaptic", "Presynaptic"] }
coords = { gW = [["PYR", "PV"], ["PYR", "PV"]], sigma = [["PYR", "PV"], ["PYR", "PV"]], kappa = [["PYR", "PV"], ["PYR", "PV"]] }
state_dict = { __call__ = ["torch", "load"], f = { __eval__ = "path" }, map_location = "cpu" }

[[plots]]
name = "pairplot"
func = "pairplot"
# kind = "reg"
vars = ['$\mathrm{det}(\mathbf{W})$', '$w_\mathrm{EE} - |w_\mathrm{II}|$', '$|w_\mathrm{II}|$', '$w_\mathrm{EE}$']
height = 2
diag_kws = { element = "step", fill = false }

[[plots]]
name = "phase_diagram"
func = "relplot"
x = '$w_\mathrm{EE} - |w_\mathrm{II}|$'
y = '$\mathrm{det}(\mathbf{W})$'
ylim = [0, { __const__ = "None" }]
height = 1.75
aspect = 1.15

[[plots]]
name = "phase_diagram_reg"
func = "lmplot"
x = '$w_\mathrm{EE} - |w_\mathrm{II}|$'
y = '$\mathrm{det}(\mathbf{W})$'
ylim = [0, { __const__ = "None" }]
height = 1.75
aspect = 1.15

[[plots]]
name = "ori_phase_diagram"
func = "relplot"
x = '$\tilde{w}_\mathrm{EE}$'
y = '$\tilde{w}_\mathrm{EI}\tilde{w}_\mathrm{IE} - \tilde{w}_\mathrm{EE}\tilde{w}_\mathrm{II}$'
ylim = [0, { __const__ = "None" }]
height = 1.75
aspect = 1.15

[[plots]]
name = "EE-II"
func = "relplot"
x = '$w_\mathrm{EE}$'
y = '$|w_\mathrm{II}|$'
height = 1.75
aspect = 1.15

[[plots]]
name = "kappa_disynaptic"
func = "displot"
x = '$\kappa_\mathrm{EI}\kappa_\mathrm{IE}$'
height = 1.75
aspect = 1.15
element = "step"
fill = false
bins = ["zero", 10]

[[plots]]
name = "tilde_w_disynaptic"
func = "displot"
x = '$\tilde{w}_\mathrm{EI}\tilde{w}_\mathrm{IE}$'
height = 1.75
aspect = 1.15
element = "step"
fill = false
bins = ["zero", 10]

