tag_names = ["path", "loss"]

[dataframes.__matrix__]
path = { __call__ = ["niarb.io", "iterdir"], path = "runs/resps_gain-1", pattern = "*.pkl", indices = { __indices__ = { __environ__ = "INDICES" } } }

[[dataframes.__include__]]
loss = { __eval__ = "float(path.stem)" }
func = ["niarb.io", "load_data"]
paths = { __eval__ = "path" }
query = "distance > 25"
cuts = { rel_ori = [0, 22.5, 67.5, 90] }
rolling = { distance = [{ __array__ = "33.7:642.1:40j" }, 60.0] }

[[plots]]
name = { __format__ = "resp_space_ori_{INDICES}" }
func = "relplot"
kind = "line"
x = "distance"
y = "dr"
hue = "rel_ori"
grid = "yzero"
height = 1.75
aspect = 1.25
palette = ["#AA2B6C", "#813D83", "#4A489E"]
legend_loc = "upper right"
facet_kws = { sharey = false, legend_out = false }
errordim = ["loss"]
errorbar = "sd"
err_kws = { linewidth = 0.5 }

[plots.mapping]
dr = '$\Delta$ response'
distance = 'Distance ($\mu$m)'
rel_ori = '$\Delta$ ori. pref. (deg)'

