tag_names = ["kind", "path", "loss"]

[dataframes.__matrix__]
kind = ["model", "data"]
path = { __call__ = ["niarb.io", "iterdir"], path = "runs/resps_gain-1", pattern = "*.pkl", indices = { __indices__ = { __environ__ = "INDICES" } } }

[[dataframes.__include__]]
loss = { __eval__ = "float(path.stem)" }

[[dataframes.__include__]]
kind = "model"
func = ["niarb.io", "load_data"]
paths = { __eval__ = "path" }
query = "distance > 25"
rolling = { distance = [{ __array__ = "33.7:642.1:40j" }, 60.0] }

[[dataframes.__include__]]
kind = "data"
func = ["niarb.viz", "sample_df"]
df = { __call__ = ["niarb.io", "load_data"], paths = "data/space.pkl" }
y = "dr"
yerr = "dr_se"
index = "index"
errorbar = "sd"

[[plots]]
name = { __format__ = "resp_space_{INDICES}" }
func = "relplot"
kind = "line"
x = "distance"
y = "dr"
style = "kind"
style_order = ["model", "data"]
grid = "yzero"
height = 1.75
aspect = 1.25
color = "black"
legend_loc = "upper right"
legend_title = false
facet_kws = { sharey = false, legend_out = false }
errordim = ["loss", "index"]
errorbar = "sd"
err_kws = { linewidth = 0.5 }

[plots.mapping]
dr = '$\Delta$ response'
distance = 'Distance ($\mu$m)'
