keep_dataframe_idx = false
tag_names = ["loss"]

[dataframes]
__ignore__ = ["path"]

[dataframes.__matrix__]
path = { __call__ = ["niarb.io", "iterdir"], path = "runs/weights", pattern = "*.feather", indices = { __indices__ = { __environ__ = "INDICES" } } }

[[dataframes.__include__]]
loss = { __eval__ = "float(path.stem)" }
func = ["niarb.io", "load_dataframe"]
filename = { __eval__ = "path" }
query = "distance < 500"
evals = { connected = "W != 0", W = "W.abs()" }
cuts = { distance = 50 }
columns = ["loss", "W", "connected", "distance", "postsynaptic_cell_type", "presynaptic_cell_type"]

[plots.__matrix__]
y = ["W", "connected"]

[[plots.__include__]]
func = "relplot"
kind = "line"
x = "distance"
hue = "postsynaptic_cell_type"
hue_order = ["PYR", "PV"]
row = "presynaptic_cell_type"
row_order = ["PYR", "PV"]
col = "loss"
grid = "yzero"
height = 1.75
aspect = 1.25
color = "black"
legend_loc = "upper right"
legend_title = false
facet_kws = { sharey = false, legend_out = false }
errorbar = "se"
err_kws = { linewidth = 0.5 }

[plots.__include__.mapping]
W = "Connection strength"
connected = "Connection prob."
distance = 'Distance ($\mu$m)'
postsynaptic_cell_type = "Postsynaptic"
presynaptic_cell_type = "Presynaptic"
loss = "Loss"

[[plots.__include__]]
name = { __format__ = "connection_strength_space_{INDICES}" }
query = "W > 0"
y = "W"

[[plots.__include__]]
name = { __format__ = "connection_probability_space_{INDICES}" }
y = "connected"

