tag_names = ["gain", "path", "loss"]

[dataframes.__matrix__]
gain = ["gain-1", { __format__ = "{KIND}_gain" }]
path = { __call__ = ["niarb.io", "iterdir"], path = { __format__ = "runs/resps_{KIND}_gain" }, pattern = "*.pkl", indices = { __indices__ = { __environ__ = "INDICES" } }, stem = true }

[[dataframes.__include__]]
loss = { __eval__ = "float(path)" }
func = ["niarb.io", "load_data"]
paths = { __format__ = "runs/resps_{gain}/{path}.pkl", gain = { __eval__ = "gain" }, path = { __eval__ = "path" } }
query = "distance > 25"
cuts = { rel_ori = [0, 22.5, 67.5, 90] }
# rolling = { rel_ori = [{ __array__ = "0:90:10j" }, 25.0] }

[[plots]]
name = { __format__ = "compare_gain_ori_ct2_{KIND}_stats_{INDICES}" }
func = "catplot"
kind = "bar"
x = "gain"
y = "dr"
hue = "rel_ori"
col = "cell_type"
col_order = ["PYR", "PV"]
stat = true
stat_kws = { test = "ttest_rel" }
errordim = "loss"
# errorbar = "pi"
errorbar = "sd"
grid = "yzero"
height = 1.75
aspect = 1
legend_loc = "upper right"
facet_kws = { sharey = false }
err_kws = { linewidth = 0.5 }

[plots.mapping]
gain = "Gain"
dr = '$\Delta$ response'
rel_ori = '$\Delta$ ori. pref. (deg)'
cell_type = "Cell type"
