batch_size = 1
dataset = { __ref__ = ["fit.toml", "validation_dataset"] }

[pipeline.model]
__ref__ = ["fit.toml", "validation_pipeline", "model"]

[pipeline.model.prob_kernel]
__call__ = ["niarb.nn", "Mul"]

[pipeline.model.prob_kernel.f]
__call__ = ["niarb.nn", "Matrix"]
# Campagnola et al. (2022):
# - E -> E: pmax = 0.1
# - E -> I: pmax = 0.225
# - I -> E: pmax = 0.275
# - I -> I: pmax = 0.3
matrix = [
    [0.1, 0.275],
    [0.225, 0.3],
]
x_keys = ["cell_type"]

[pipeline.model.prob_kernel.g]
__call__ = ["niarb.nn", "Mul"]

[pipeline.model.prob_kernel.g.f]
__call__ = ["niarb.nn", "Laplace"]
d = 0
# Fit to Rossi et al. (2020) with d = 0 kernel:
# - E -> E: sigma = 109.3 μm
# - I -> E: sigma = 81.0 μm
# Assume E -> I same width as I -> E, I -> I same with as E -> E
sigma = [
    [109.3, 81.0],
    [81.0, 109.3],
]
normalize = true
x_keys = ["space", "cell_type"]

[pipeline.model.prob_kernel.g.g]
__call__ = ["niarb.nn", "Tuning"]
kappa = [
    [0.198, 0.0],
    [0.0, 0.0],
]
x_keys = ["ori", "cell_type"]

[state_dict]
__call__ = ["niarb.io", "load_state_dict"]
modify = "gW"
mode = "scale"
value = { __call__ = ["builtins", "float", { __environ__ = "GAIN" }] }

[state_dict.path]
__call__ = ["niarb.io", "iterdir"]
path = "fits"
pattern = "*.pt"
indices = { __call__ = ["builtins", "int", { __environ__ = "SLURM_ARRAY_TASK_ID" }] }

[out]
__format__ = "runs/resps_gain-{GAIN}/{filename}.pkl"

[out.filename]
__call__ = ["niarb.io", "iterdir"]
path = "fits"
pattern = "*.pt"
stem = true
indices = { __call__ = ["builtins", "int", { __environ__ = "SLURM_ARRAY_TASK_ID" }] }
