batch_size = 1
dataset = { __ref__ = ["fit.toml", "validation_dataset"] }
# Campagnola et al. (2022):
# - E -> E: σ = 127 μm, pmax = 0.1
# - E -> I: σ = 100 μm, pmax = 0.225
# - I -> E: σ = 97 μm, pmax = 0.275
# - I -> I: σ = 127 μm, pmax = 0.3
# Simulation region: U = 900 μm x 900 μm
# Number of neurons: N = 24000
# Expected number of presynaptic connections per neurons: pmax * sum_i exp(-r_i^2/(2σ^2)) = pmax * N / V * \iint_U \exp(-r^2/(2σ^2)) dxdy
# - E -> E: 0.1 * (0.85 * 24000) * 0.125014 = 225.029
# - E -> I: 0.225 * (0.85 * 24000) * 0.0775691 = 356.042
# - I -> E: 0.275 * (0.15 * 24000) * 0.0729853 = 72.2554
# - I -> I: 0.3 * (0.15 * 24000) * 0.125014 = 135.015
# Expected number of presynaptic connections for E = 327.284
# Expected number of presynaptic connections for I = 491.057
# Expected number of presynaptic connections per neurons = 327.284 * 0.85 + 491.057 * 0.15 = 351.85
pipeline.model = { __ref__ = ["fit.toml", "validation_pipeline", "model"], N_synapses =  352 }

[state_dict]
__call__ = ["niarb.io", "load_state_dict"]
modify = "gW"
mode = "scale"
value = { __call__ = ["builtins", "float", { __environ__ = "GAIN" }] }

[state_dict.path]
__call__ = ["niarb.io", "iterdir"]
path = "fits"
pattern = "*.pt"
indices = { __call__ = ["builtins", "int", { __environ__ = "SLURM_ARRAY_TASK_ID" }] }

[out]
__format__ = "runs/resps_gain-{GAIN}/{filename}.pkl"

[out.filename]
__call__ = ["niarb.io", "iterdir"]
path = "fits"
pattern = "*.pt"
stem = true
indices = { __call__ = ["builtins", "int", { __environ__ = "SLURM_ARRAY_TASK_ID" }] }
