batch_size = 1
dataset = { __ref__ = ["fit.toml", "validation_dataset"] }
# Campagnola et al. (2022):
# - E -> E: σ = 127 μm, pmax = 0.1
# - E -> I: σ = 100 μm, pmax = 0.225
# - I -> E: σ = 97 μm, pmax = 0.275
# - I -> I: σ = 127 μm, pmax = 0.3
[pipeline.model]
__ref__ = ["fit.toml", "validation_pipeline", "model"]
W_max = 0.5

[pipeline.model.prob_kernel]
__call__ = ["niarb.nn", "Mul"]

[pipeline.model.prob_kernel.f]
__call__ = ["niarb.nn", "MatrixKernel"]
matrix = [
    [0.1, 0.275],
    [0.225, 0.3],
]
x_keys = ["cell_type"]

[pipeline.model.prob_kernel.g]
__call__ = ["niarb.nn", "Mul"]

[pipeline.model.prob_kernel.g.f]
__call__ = ["niarb.nn", "GaussianKernel"]
sigma = [
    [127.0, 97.0],
    [100.0, 127.0],
]
x_keys = ["space", "cell_type"]

[pipeline.model.prob_kernel.g.g]
__call__ = ["niarb.nn", "TuningKernel"]
kappa = [
    [0.198, 0.0],
    [0.0, 0.0],
]
x_keys = ["ori", "cell_type"]

[state_dict]
__call__ = ["niarb.io", "load_state_dict"]
modify = "gW"
mode = "scale"
value = { __call__ = ["builtins", "float", { __environ__ = "GAIN" }] }

[state_dict.path]
__call__ = ["niarb.io", "iterdir"]
path = "fits"
pattern = "*.pt"
indices = { __call__ = ["builtins", "int", { __environ__ = "SLURM_ARRAY_TASK_ID" }] }

[out]
__format__ = "runs/resps_gain-{GAIN}/{filename}.pkl"

[out.filename]
__call__ = ["niarb.io", "iterdir"]
path = "fits"
pattern = "*.pt"
stem = true
indices = { __call__ = ["builtins", "int", { __environ__ = "SLURM_ARRAY_TASK_ID" }] }
