batch_size = 1
# dataset = { __ref__ = ["fit.toml", "validation_dataset"] }

[dataset]
abs_window = [600.0, 600.0]
N_instantiations = 10

[dataset.neurons]
N = 15000
variables = ["cell_type", "space", "ori"]
cell_types = ["PYR", "PV"]
cell_probs = [0.85, 0.15]
space_extent = [900.0, 900.0]
min_dist = 3.0
w_dims = []

[dataset.perturbations.configs.__matrix__]
N = [1]
cell_probs = [{ PYR = 1.0 }]
space = [["uniform", [550.0, 550.0]]]
repeats = [5]

[dataset.metrics]
distance = "min_distance_to_ensemble"
rel_ori = "abs_relative_ori"

[pipeline.model]
__ref__ = ["fit.toml", "validation_pipeline", "model"]
dense = false
monotonic_strength = true

[pipeline.model.prob_kernel.cell_type]
__call__ = ["niarb.nn", "Matrix"]
x_keys = ["cell_type"]
# Campagnola et al. (2022):
# - E -> E: pmax = 0.1
# - E -> I: pmax = 0.225
# - I -> E: pmax = 0.275
# - I -> I: pmax = 0.3
matrix = [
    [0.1, 0.275],
    [0.225, 0.3],
]

[pipeline.model.prob_kernel.space]
__call__ = ["niarb.nn", "Gaussian"]
x_keys = ["space"]

[pipeline.model.prob_kernel.space.sigma]
__call__ = ["niarb.nn", "Matrix"]
x_keys = ["cell_type"]
# Fit to Rossi et al. (2020) with gaussian kernel:
# - E -> E: sigma = 144.9 μm
# - I -> E: sigma = 107.8 μm
# Assume E -> I same width as I -> E, I -> I same with as E -> E
matrix = [
    [144.9, 107.8],
    [107.8, 144.9],
]

[pipeline.model.prob_kernel.ori]
__call__ = ["niarb.nn", "Tuning"]
x_keys = ["ori"]

[pipeline.model.prob_kernel.ori.kappa]
__call__ = ["niarb.nn", "Matrix"]
x_keys = ["cell_type"]
matrix = [
    [0.198, 0.0],
    [0.0, 0.0],
]

[state_dict]
__call__ = ["niarb.io", "load_state_dict"]
modify = "gW"
mode = "scale"
value = { __call__ = ["builtins", "float", { __environ__ = "GAIN" }] }

[state_dict.path]
__call__ = ["niarb.io", "iterdir"]
path = "fits"
pattern = "*.pt"
indices = { __call__ = ["builtins", "int", { __environ__ = "SLURM_ARRAY_TASK_ID" }] }

[out]
__format__ = "runs/resps_gain-{GAIN}/{filename}.pkl"

[out.filename]
__call__ = ["niarb.io", "iterdir"]
path = "fits"
pattern = "*.pt"
stem = true
indices = { __call__ = ["builtins", "int", { __environ__ = "SLURM_ARRAY_TASK_ID" }] }
