batch_size = 1
dataset = { __ref__ = ["fit.toml", "validation_dataset"], N_instantiations = 1, model_kwargs = { output = "weight" } }
# Campagnola et al. (2022):
# - E -> E: σ = 127 μm, pmax = 0.1
# - E -> I: σ = 100 μm, pmax = 0.225
# - I -> E: σ = 97 μm, pmax = 0.275
# - I -> I: σ = 127 μm, pmax = 0.3
# Simulation region: U = 900 μm x 900 μm
# Number of neurons: N = 24000
# Expected number of presynaptic connections per neurons: pmax * sum_i exp(-r_i^2/(2σ^2)) = N * pmax / Z * \iint_U \exp(-r^2/(2σ^2)) * r dxdy, where Z = \iint_U r dxdy = 2.78914e8 μm^2
# - E -> E: (0.85 * 24000) * 0.1 * 0.0576908 = 117.7
# - E -> I: (0.85 * 24000) * 0.225 * 0.0282323 = 129.6
# - I -> E: (0.15 * 24000) * 0.275 * 0.0257675 = 25.5
# - I -> I: (0.15 * 24000) * 0.3 * 0.0576908 = 62.3
# Expected number of E presynaptic connections = 143
# Expected number of I presynaptic connections = 192
# Expected number of connections per neurons = 143 * 0.85 + 192 * 0.15 = 150
pipeline.model = { __ref__ = ["fit.toml", "validation_pipeline", "model"], N_synapses =  150 }

[state_dict]
__call__ = ["niarb.io", "load_state_dict"]

[state_dict.path]
__call__ = ["niarb.io", "iterdir"]
path = "fits"
pattern = "*.pt"
indices = { __call__ = ["builtins", "int", { __environ__ = "SLURM_ARRAY_TASK_ID" }] }

[out]
__format__ = "runs/weights/{filename}.pt"

[out.filename]
__call__ = ["niarb.io", "iterdir"]
path = "fits"
pattern = "*.pt"
stem = true
indices = { __call__ = ["builtins", "int", { __environ__ = "SLURM_ARRAY_TASK_ID" }] }
